### PR TITLE
Create scholar.txt

### PR DESCRIPTION
**Pull request by no-egrets**
New command ?scholar, similar to validation but more simple, that allows users to enter a secret command to earn a role. Intended to be used to encourage reading of the FAQ - just hide the command near the bottom. Adapted from my own implementation.

### CODE REVIEW

**Comment by NexWasTaken** [comment]
I like this command.

**Comment by cmdwm** [comment]
I agree with Nex, this is a great idea!

**Comment by Swordington** [comment]
Agreed, this is quite a good command!!

**Comment by Swordington** [comment]
Merged on a 3-0 vote.

**Comment by RenderedPix** [comment]
This was actually used in the verification channel. Already made, but you compressed it. Nice work!

**Pull request merged**
