### PR TITLE
Verify-application command

### PR DESCRIPTION
**Pull request by CronixZero**
READ README!

### CODE REVIEW

**Review by Swordington — CHANGES_REQUESTED** [review]
There are multiple errors that must be fixed before we even consider this command.

**Comment by CronixZero** [comment]
No there are no errors. You only must write in your website

Please use this command on our server: ?verify-application c/n 5g88wqhd, the command is working on my own server so the command cant have any errors and Ive testet it there is 1 problem but thats a Dyno problem and the dyno problem is that when 2 people in the sa.e time their application verificate then the bot doesnt know that and sends 2 times the same name but if the owner of the server has a log he can look into that and knows it

**Comment by Swordington** [comment]
I'm sorry, but we are unable to understand that response. Would you please rephrase that? Furthermore; there are a multitude of spelling issues that **must be fixed** to be considered.

**Comment by CronixZero** [comment]
The command hasnt any mistakes / errors

**Comment by Swordington** [comment]
There are a multitude of errors, please fix them or we will close this PR.

**Comment by Swordington** [comment]
As there was no attempt to fix the errors, **we are closing this PR.**

**Pull request closed without merging**
