### PR TITLE
Punish Roulette

### PR DESCRIPTION
**Pull request by Smaltin**
Picks between a few preset punishments that can be modified. The user will be notified of their punishment. Then, server admins can carry out the punishment.
Format: "?commandname @userbeingpunished"

### CODE REVIEW

**Comment by advaith1** [comment]
Hm, shouldn't mods punish users based on how serious their infraction was? I just don't see how this is really that good as a command.

**Comment by Smaltin** [comment]
It's a fun command.

**Comment by cmdwm** [comment]
Agreeing with Advaith...
It's not fun for the user being punished.
And the user should be punished accordingly to their action.
 - Will

**Review by Swordington — DISMISSED** [review]
I think that as a general rule this type of command could be definitely abused / abusive, and a mod should take appropriate actions against a user instead of making it a game.

**Comment by Swordington** [comment]
Mods & Admins should use standard commands when dealing with punishments, it's important that moderating is not a game.

**Comment by advaith1** [comment]
(Adding a little blurb here)
The team has voted on this and we decided against adding it. You may see this as a fun command but this will likely influence moderators into giving users punishments they don't deserve. We do not want to endorse this kind of random punishment, punishments should fit the crime done.
However, remember that you can still submit other commands!

**Pull request closed without merging**
