### PR TITLE
Nickname Requests Commands

### PR DESCRIPTION
**Pull request by CraftyCat05**

### CODE REVIEW

**Comment by CraftyCat05** [comment]
For Deny for Staff
Role Require: Staff
Usage: !nden <user that did the request> <no so cool denied nickname>
Description: Gives DM to user that the nickname was denied.

**Comment by CraftyCat05** [comment]
For Approve for Staff
Roles Required: Staff
Usage: !napp <user to nick> <cool nickname you approved>
Description: To approve the nickname request. DMs the user a message saying that the nick was approved and given. Gives nick.

**Comment by CraftyCat05** [comment]
For Nickname Request for Users
Role Requirement: None
Usage: !nickname <your crazy cool meant to be nickname>
Description: Used to let users request a nickname for themselves, but needs to be approved.
Part one: Puts a confirmation that the request was submitted into the channel the command was used - For user
Part two: Puts a embed into a nickname log channel for a staff member to approve or deny the request - For staff

**Comment by cmdwm** [comment]
I don't understand why there's a whole process for someone to change their username lol

**Comment by CraftyCat05** [comment]
Some servers like to have a Nickname Request feature so that there isn't spam nickname's or racist ones. This is just for others to use if they want it.

**Comment by cmdwm** [comment]
So they (admins) can change nickname manually, you dont need a whole job application each time for a nickname command. :/ jmo - lmao but i mean its cool for those who need it

**Comment by NexWasTaken** [comment]
I really like this command but unfortunately other staff members don't like it. Anyways good job man. :(

**Comment by CraftyCat05** [comment]
So is it denied?

**Comment by NexWasTaken** [comment]
As of now, your pr has a 3-2 vote. 3 being in the favor of merging but not everybody has voted. So ¯\_(ツ)_/¯

**Comment by advaith1** [comment]
@CraftyCat05 Congratulations on getting your PR merged! Are you in our Discord server?

**Comment by CraftyCat05** [comment]
@advaith1 I certainly am, thanks for accepting!

**Comment by advaith1** [comment]
what's your username?

**Comment by CraftyCat05** [comment]
CraftyCat05 - I don't change lol @advaith1

**Pull request merged**
