### PR TITLE
Add waw command

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by advaith1** [comment]
what's the point of this 🤔

**Comment by ghost** [comment]
🤔Maybe, it could greet people u wanna talk to! Like if they won't respond, waw at them and they will!

**Comment by cmdwm** [comment]
Bad command. Useless idea.

**Comment by RenderedPix** [comment]
Denied.

**Comment by RenderedPix** [comment]
Major Vote ^

**Pull request closed without merging**
