### PR TITLE
clear-dm command

### PR DESCRIPTION
**Pull request by CronixZero**
this is a command where you can "clear" your dms from dyno with

### CODE REVIEW

**Comment by no-egrets** [comment]
Just to be sure about this, @CronixZero, the command responds with a ton of whitespace to effectively scroll down whichever channel it's used in, in order to act as a break in conversation?

**Comment by CronixZero** [comment]
Ok, problem the command was {dm:{user} and then all that is in this

**Comment by no-egrets** [comment]
Ah, so your intent is that the bot DMs the user with a ton of whitespace? Could you give an example use case?

**Comment by CronixZero** [comment]
I can invite you to my server where the command is used :o

**Comment by no-egrets** [comment]
That's not necessary, I'm not trying to ascertain _whether_ it works but rather how, from your perspective, other Dyno users would find it useful?

**Comment by CronixZero** [comment]
Ahhh, yes

**Comment by advaith1** [comment]
Isn't this basically a copy of https://github.com/DynoCC/Dyno-Custom-Commands/blob/master/Utilities/dmclean.txt @CronixZero

**Comment by CronixZero** [comment]
Ive seen on the discord that this isnt working :o

**Comment by Swordington** [comment]
It seems your goal is to fix an already existing command. If that is your goal, please make a PR to fix _that_ as opposed to creating a new command.

**Comment by CronixZero** [comment]
Ok

**Comment by Swordington** [comment]
Wonderful! Closing this PR at this time.

**Pull request closed without merging**
