### PR TITLE
add a nicer !user menu

### PR DESCRIPTION
**Pull request by darkgodz**
just because it's look nicer :)

### CODE REVIEW

**Comment by darkgodz** [comment]
untitled2


here a photo of how it's look.

**Comment by RenderedPix** [comment]
@darkgodz I'll cast a vote.

**Review by RenderedPix — APPROVED** [review]
Approved by me.

**Comment by advaith1** [comment]
Denied because helpers voted to deny it and it serves no purpose. The built-in userinfo command does this and more.

**Pull request closed without merging**
