### PR TITLE
Create report.txt

### PR DESCRIPTION
**Pull request by ghost**
When users do `?report {UserToReport} {Evidence} {Offence}` it will send the information to #reports and mention the @ReportsTeam so they know a new report has come in. The command then goes back to #report-here and lets the user know the report was successfully created, and that the @ReportsTeam will get back to them shortly. 

This is just a basic report command, useful for moderating when staff aren't on, as users can report them easily, for staff to see when they are on.

### CODE REVIEW

**Review by CraftyCat05 — APPROVED** [review]
I like it, we shall see what the others think though. Good job and nice command!

**Review by redstonedesigner — CHANGES_REQUESTED** [review]
1) The announce function is incorrect on line 2.
```
{&ReportsTeam}
{!announce <#channel-name> <report text>}
```
2) I think you would be better off using {respond:} instead of announce for the first announce command.

**Comment by ghost** [comment]
@redstonedesigner I was thinking of doing that but then remembered you can’t have both respond and announce on default dyno (you can with premium though as it sends as a webhook).

When I get home I’ll come up with a fix.

**Comment by NexWasTaken** [comment]
We already have a `?report` command. Why do you think we need another one?

**Review by CraftyCat05 — CHANGES_REQUESTED** [review]
Forgot that we already have a report command, sorry.

**Review by cmdwm — CHANGES_REQUESTED** [review]
*already have this cmd, nice job tho

**Comment by redstonedesigner** [comment]
Closed with 1-5 against.

**Comment by RenderedPix** [comment]
Labeled Pull Request #46

**Pull request closed without merging**
