### PR TITLE
Introduced CC 'crownme'

### PR DESCRIPTION
**Pull request by no-egrets**
New command 'crownme' - a simple game where only one person can hold the role of Caesar, and anyone can claim it. Requires an existing role of 'Caesar', preferably with a distinct color. Could give Caesar special privileges, like the ability to post embeds, or use external emoji, or to mute other users. Since the calling message is deleted (to cut down on bot spam), you'll need to document the command somewhere.

### CODE REVIEW

**Comment by ghost** [comment]
Interesting command. I probably won't enable the role to have special privileges because the entire chat will just be people spamming ?crownme to get the role.

Seems good.

**Comment by advaith1** [comment]
@amosharper BTW, are you in our Discord server?

**Comment by no-egrets** [comment]
Yup, @advaith1, I'll ping you on Discord.

**Comment by ghost** [comment]
I've added this command's preview to the Mini-Games' section.

**Pull request merged**
