### PR TITLE
Big fella.txt

### PR DESCRIPTION
**Pull request by Bohen-Cegnaud**
Ya'll mind if i praise the lord?

### CODE REVIEW

**Comment by advaith1** [comment]
@Bohen-Cegnaud what's the use of this command?

**Comment by thatrelevantperson** [comment]
This PR is about to be closed and denied as we see no use for it.

**Comment by whasonyt** [comment]
Praises with you 🙏

**Comment by Swordington** [comment]
Since there has been no reply we are closing this PR.

**Comment by Bohen-Cegnaud** [comment]
Oh shoot sorry, I didn’t see this email! It was for my personal discord
server

**Pull request closed without merging**
