### PR TITLE
A ragequit command.

### PR DESCRIPTION
**Pull request by NexWasTaken**
A fun command to prank users who don't know what it is used for.

### CODE REVIEW

**Comment by whasonyt** [comment]
Can you give an example of the command being used, i dont understad....

**Comment by cmdwm** [comment]
Kicking users for doing nothing isnt that smart if you want to grow your server member count.

**Comment by RenderedPix** [comment]
UNSAFE command. Not thoroughly put out, due to the lack of security/protection. Anyone can use the command and raid your whole entire server.

**Comment by advaith1** [comment]
@RenderedPix how the frick do you "raid" a server by leaving it 🤔

**Comment by Swordington** [comment]
Yes, ummmm. This command could be a bit better if it tempmuted the user for maybe 30sec. But kicking is a bit extreme. And how does one raid by leaving?

**Comment by NexWasTaken** [comment]
Just a prank command guys. Nothing more. It won't get your server "raided" or decrease your server member count (they can just join back).

**Comment by RenderedPix** [comment]
"kicking" with out any requiring any permissions or roles, allows anyone to kick every single person

**Comment by RenderedPix** [comment]
https://gyazo.com/b53c561e60fa564db4c514940814381d
{require:} is not there, so that allows everyone to use it.

**Comment by advaith1** [comment]
@RenderedPix yes but you can only kick yourself

**Comment by NexWasTaken** [comment]
It is a prank command. What's the fun in kicking a user when you can prank them.

**Comment by redstonedesigner** [comment]
I don't like this command very much and it doesn't make sense to me.
There is the "Leave Server" option, or the moderators should be using appropriate commands and not fun ones.

After a 0-4 vote in favour of rejecting this PR, this Pull Request is now getting closed.

Thanks,
Redstone
(Custom Command) Helper
Dyno Custom Commands

**Pull request closed without merging**
