### PR TITLE
Create command suggest

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by redstonedesigner — CHANGES_REQUESTED** [review]
The `{respond:#suggestions}` should be on a different line to everything else.

Apart from that, you are good to go.

**Review by CraftyCat05 — CHANGES_REQUESTED** [review]
I suggest you do what Redstone Designer said, and make it also be an embed using `?announce`.

Otherwise, I like it and makes servers need one less bot for suggestions.

**Comment by ghost** [comment]
Changed.

**Review by redstonedesigner — APPROVED** [review]

**Review by CraftyCat05 — APPROVED** [review]

**Comment by Darqness** [comment]
We already have a suggestion command.

**Comment by cmdwm** [comment]
Hello, I'm pretty sure this was copied from my YouTube video. I approve the PR but please try to make your own commands.

**Comment by NexWasTaken** [comment]
1. Command is poorly written and can be improved.
2. We have a suggest command already.
3. Come up with something interesting.

**Comment by cmdwm** [comment]
To cover this more, here's a link to the YouTube  video I explained this in. 

https://youtu.be/npikhuvFZGs
....
This may be a coincidence but I'm certain you have copied my work. If you use someone else's work, feel free to post a PR but **give them credit**.

**Review by cmdwm — APPROVED** [review]

**Comment by advaith1** [comment]
Closed with a 2 - 7  vote.

**Comment by RenderedPix** [comment]
Labeled Pull Request #45

**Pull request closed without merging**
