### PR TITLE
apply-add command

### PR DESCRIPTION
**Pull request by CronixZero**
with that command you can show your staff a application of a member!

### CODE REVIEW

**Comment by Swordington** [comment]
Hi there and thanks for submitting a command! What would be a possible use case for this command and how is it different from other commands already in DCC's repo?

**Comment by CronixZero** [comment]
1. When you recieve from a user a application you can do this command that the team can vote for the application

2. Its new

**Comment by Swordington** [comment]
I'm sorry, we don't understand your first point. Would you please rephrase it so we can understand your intent better?

**Comment by CronixZero** [comment]
When you recieve a application of a member that wants to be in you staff you use this to send a message in a channel where the staff can vote for the application

**Comment by Swordington** [comment]
Thank you. Your command is being considered by our team.

**Comment by CronixZero** [comment]
Ok

**Review by Swordington — CHANGES_REQUESTED** [review]
There are many errors in this that need fixing.

**Comment by Swordington** [comment]
Hi there! If there is no more activity on this Pull Request for 24 hours, we will consider it abandoned and will close it.

**Comment by thatrelevantperson** [comment]
My feedback: For this custom command, I don't see where you can identify the application. Maybe assign an ID number to the application then have the person running the command put the ID number of the application sent.

**Comment by Swordington** [comment]
Due to no activity, we are assuming abandonment. Closing.

**Pull request closed without merging**
