### PR TITLE
bann.txt

### PR DESCRIPTION
**Pull request by KingOof13**
It's a funny way to trick someone into thinking they or someone got banned.

### CODE REVIEW

**Review by Swordington — CHANGES_REQUESTED** [review]
Hi! This command is not functional: The command does not effectively show who is being fake baned, nor does it have a valid use-case.

**Comment by Swordington** [comment]
Hello, please review the above note to continue with the approval process for this command.

**Comment by KingOof13** [comment]
Sorry I'm new to that and I acendentally made that you can delete it.

**Comment by KingOof13** [comment]
I am sorry I did not mean to do a pull request. Still new to this and will never happen again

**Comment by Swordington** [comment]
ok..? You were able to fix the command and it could've been pushed.

Have a nice day!
MrMastersword

**Pull request closed without merging**
